version: '3.1'
services: 
  drupal:
    container_name: drupal_web
    volumes: 
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    image: drupal
    ports: 
      - "8085:80"
    networks: 
      - my-net
  postgres:
    container_name: postgres_db
    image: postgres:10
    environment: 
      POSTGRES_PASSWORD: example
    volumes: 
      - progres_data:/var/lib/postgresql/data
    networks: 
      - my-net
volumes: 
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:  
  progres_data:    
networks: 
  my-net: 