version: '3.7'
services: 
  wordpress:
    depends_on: 
      - db
    container_name: wp
    volumes: 
      - "$PWD/html:/var/www/html"
    image: wordpress
    ports: 
      - "81:80"
    environment: 
      WORDPRESS_DB_HOST: wp-mysql::33060
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks: 
      - my-net
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: wp-mysql
    volumes: 
      - $PWD/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports: 
      - "3307:3306"
    networks: 
      - my-net
networks: 
  my-net:
